# -*- coding: utf-8 -*-
"""Copy of LerPDFemVozAlta.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q_7sG0qKispiXKWuSTVgaroIIR0yykYz
"""

!pip install gTTS
!pip install PyPdf2

from gtts import gTTS
from IPython.display import Audio
import PyPDF2

file =open('/content/BGSample-PO-0712.pdf', 'rb')
reader = PyPDF2.PdfFileReader(file)
pagina1 = reader.getPage(0)
pdfData = pagina1.extractText()

tts = gTTS(pdfData, lang='pt-br')
tts.save('1.wav')
sound_file = '1.wav'
Audio(sound_file, autoplay=True)